
"""add_engagement_type_to_projects

Revision ID: 20c1ec8d8a44
Revises: 20260120_0016
Create Date: 2026-01-21 17:41:39.207865
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '20c1ec8d8a44'
down_revision = '20260120_0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_packages_name', table_name='credit_packages')
    op.create_index('ix_credit_packages_name', 'credit_packages', ['name'], unique=False)
    op.create_unique_constraint(None, 'credit_packages', ['name'])
    op.drop_constraint('uq_notification_preferences_user_workspace_type', 'notification_preferences', type_='unique')
    op.add_column('projects', sa.Column('engagement_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('team', sa.JSON(), nullable=True))
    op.drop_constraint('uq_team_members_team_user', 'team_members', type_='unique')
    op.alter_column('users', 'two_factor_backup_codes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'two_factor_backup_codes',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.create_unique_constraint('uq_team_members_team_user', 'team_members', ['team_id', 'user_id'])
    op.drop_column('projects', 'team')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'engagement_type')
    op.create_unique_constraint('uq_notification_preferences_user_workspace_type', 'notification_preferences', ['user_id', 'workspace_id', 'preference_type'])
    op.drop_constraint(None, 'credit_packages', type_='unique')
    op.drop_index('ix_credit_packages_name', table_name='credit_packages')
    op.create_index('ix_credit_packages_name', 'credit_packages', ['name'], unique=True)
    # ### end Alembic commands ###




