
"""add core domain tables

Revision ID: da2fd07bfb00
Revises: 20260106_0002
Create Date: 2026-01-07 20:53:14.985166
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import app.db.base


revision = "da2fd07bfb00"
down_revision = "20260106_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_password_reset_user_code')
    )
    op.create_index('ix_password_resets_code', 'password_resets', ['code'], unique=False)
    op.create_index('ix_password_resets_expires', 'password_resets', ['expires_at'], unique=False)
    op.create_index('ix_password_resets_user', 'password_resets', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('owner_id', app.db.base.GUID(), nullable=False),
    sa.Column('team_size', sa.String(length=50), nullable=True),
    sa.Column('data_handling', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_workspaces_slug')
    )
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_index('ix_workspaces_slug', 'workspaces', ['slug'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=True),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', app.db.base.GUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_created', 'activity_log', ['created_at'], unique=False)
    op.create_index('ix_activity_entity', 'activity_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_activity_user', 'activity_log', ['user_id'], unique=False)
    op.create_index('ix_activity_workspace', 'activity_log', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_workspace', 'projects', ['workspace_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('table_columns', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_category', 'templates', ['category'], unique=False)
    op.create_index('ix_templates_public', 'templates', ['is_public'], unique=False)
    op.create_index('ix_templates_workspace', 'templates', ['workspace_id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'metric_type', 'period_start', name='uq_usage_metric_period')
    )
    op.create_index('ix_usage_metrics_period', 'usage_metrics', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_usage_metrics_workspace', 'usage_metrics', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_user')
    )
    op.create_index('ix_workspace_members_invited_email_unique', 'workspace_members', ['workspace_id', 'invited_email'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('ix_workspace_members_user', 'workspace_members', ['user_id'], unique=False)
    op.create_index('ix_workspace_members_workspace', 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('scopes',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('project_id', app.db.base.GUID(), nullable=True),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scopes_created_by'), 'scopes', ['created_by'], unique=False)
    op.create_index('ix_scopes_project', 'scopes', ['project_id'], unique=False)
    op.create_index('ix_scopes_status', 'scopes', ['status'], unique=False)
    op.create_index('ix_scopes_workspace', 'scopes', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=True),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', app.db.base.GUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_scope', 'documents', ['scope_id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['processing_status'], unique=False)
    op.create_index('ix_documents_workspace', 'documents', ['workspace_id'], unique=False)
    op.create_table('favourites',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_id', name='uq_favourites_user_scope')
    )
    op.create_index('ix_favourites_scope', 'favourites', ['scope_id'], unique=False)
    op.create_index('ix_favourites_user', 'favourites', ['user_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('cover_color', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('slide_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('shared_link', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_scope', 'proposals', ['scope_id'], unique=False)
    op.create_index('ix_proposals_shared_link', 'proposals', ['shared_link'], unique=True)
    op.create_index('ix_proposals_status', 'proposals', ['status'], unique=False)
    op.create_index('ix_proposals_workspace', 'proposals', ['workspace_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('design_hours', sa.Integer(), nullable=False),
    sa.Column('frontend_hours', sa.Integer(), nullable=False),
    sa.Column('backend_hours', sa.Integer(), nullable=False),
    sa.Column('qa_hours', sa.Integer(), nullable=False),
    sa.Column('created_by', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotations_scope', 'quotations', ['scope_id'], unique=False)
    op.create_index('ix_quotations_status', 'quotations', ['status'], unique=False)
    op.create_index('ix_quotations_workspace', 'quotations', ['workspace_id'], unique=False)
    op.create_table('scope_sections',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scope_sections_order', 'scope_sections', ['scope_id', 'order_index'], unique=False)
    op.create_index('ix_scope_sections_scope', 'scope_sections', ['scope_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('scope_id', app.db.base.GUID(), nullable=False),
    sa.Column('section_id', app.db.base.GUID(), nullable=True),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('parent_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['scope_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_scope', 'comments', ['scope_id'], unique=False)
    op.create_index('ix_comments_section', 'comments', ['section_id'], unique=False)
    op.create_index('ix_comments_user', 'comments', ['user_id'], unique=False)
    op.create_table('proposal_slides',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('proposal_id', app.db.base.GUID(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('slide_type', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'slide_number', name='uq_proposal_slides_proposal_slide_number')
    )
    op.create_index('ix_proposal_slides_order', 'proposal_slides', ['proposal_id', 'order_index'], unique=False)
    op.create_index('ix_proposal_slides_proposal', 'proposal_slides', ['proposal_id'], unique=False)
    op.create_table('proposal_views',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('proposal_id', app.db.base.GUID(), nullable=False),
    sa.Column('viewer_email', sa.String(length=255), nullable=True),
    sa.Column('viewer_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposal_views_email', 'proposal_views', ['viewer_email'], unique=False)
    op.create_index('ix_proposal_views_proposal', 'proposal_views', ['proposal_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('quotation_id', app.db.base.GUID(), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('feature', sa.Text(), nullable=True),
    sa.Column('interactions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('design', sa.Integer(), nullable=False),
    sa.Column('frontend', sa.Integer(), nullable=False),
    sa.Column('backend', sa.Integer(), nullable=False),
    sa.Column('qa', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotation_items_order', 'quotation_items', ['quotation_id', 'order_index'], unique=False)
    op.create_index('ix_quotation_items_quotation', 'quotation_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotation_items_quotation', table_name='quotation_items')
    op.drop_index('ix_quotation_items_order', table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index('ix_proposal_views_proposal', table_name='proposal_views')
    op.drop_index('ix_proposal_views_email', table_name='proposal_views')
    op.drop_table('proposal_views')
    op.drop_index('ix_proposal_slides_proposal', table_name='proposal_slides')
    op.drop_index('ix_proposal_slides_order', table_name='proposal_slides')
    op.drop_table('proposal_slides')
    op.drop_index('ix_comments_user', table_name='comments')
    op.drop_index('ix_comments_section', table_name='comments')
    op.drop_index('ix_comments_scope', table_name='comments')
    op.drop_index('ix_comments_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_scope_sections_scope', table_name='scope_sections')
    op.drop_index('ix_scope_sections_order', table_name='scope_sections')
    op.drop_table('scope_sections')
    op.drop_index('ix_quotations_workspace', table_name='quotations')
    op.drop_index('ix_quotations_status', table_name='quotations')
    op.drop_index('ix_quotations_scope', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_proposals_workspace', table_name='proposals')
    op.drop_index('ix_proposals_status', table_name='proposals')
    op.drop_index('ix_proposals_shared_link', table_name='proposals')
    op.drop_index('ix_proposals_scope', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_favourites_user', table_name='favourites')
    op.drop_index('ix_favourites_scope', table_name='favourites')
    op.drop_table('favourites')
    op.drop_index('ix_documents_workspace', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_scope', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_scopes_workspace', table_name='scopes')
    op.drop_index('ix_scopes_status', table_name='scopes')
    op.drop_index('ix_scopes_project', table_name='scopes')
    op.drop_index(op.f('ix_scopes_created_by'), table_name='scopes')
    op.drop_table('scopes')
    op.drop_index('ix_workspace_members_workspace', table_name='workspace_members')
    op.drop_index('ix_workspace_members_user', table_name='workspace_members')
    op.drop_index('ix_workspace_members_invited_email_unique', table_name='workspace_members', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_table('workspace_members')
    op.drop_index('ix_usage_metrics_workspace', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_period', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index('ix_templates_workspace', table_name='templates')
    op.drop_index('ix_templates_public', table_name='templates')
    op.drop_index('ix_templates_category', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_projects_workspace', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_activity_workspace', table_name='activity_log')
    op.drop_index('ix_activity_user', table_name='activity_log')
    op.drop_index('ix_activity_entity', table_name='activity_log')
    op.drop_index('ix_activity_created', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index('ix_workspaces_slug', table_name='workspaces')
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_password_resets_user', table_name='password_resets')
    op.drop_index('ix_password_resets_expires', table_name='password_resets')
    op.drop_index('ix_password_resets_code', table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###


