
"""add_reminders_table

Revision ID: f28a49638d7d
Revises: 20260122_191745
Create Date: 2026-01-23 13:13:17.421923
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.base

revision = 'f28a49638d7d'
down_revision = '20260122_191745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('project_id', app.db.base.GUID(), nullable=True),
    sa.Column('scope_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_by', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_created_by', 'reminders', ['created_by'], unique=False)
    op.create_index('ix_reminders_date', 'reminders', ['date'], unique=False)
    op.create_index('ix_reminders_project', 'reminders', ['project_id'], unique=False)
    op.create_index('ix_reminders_type', 'reminders', ['type'], unique=False)
    op.create_index('ix_reminders_workspace', 'reminders', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_workspace', table_name='reminders')
    op.drop_index('ix_reminders_type', table_name='reminders')
    op.drop_index('ix_reminders_project', table_name='reminders')
    op.drop_index('ix_reminders_date', table_name='reminders')
    op.drop_index('ix_reminders_created_by', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###




